; STM32F411CEU6 Controller mit NRF24L01 Sender
; Target: Black Pill (STM32F411CEU6)

[env:blackpill_f411]
platform = ststm32
board = blackpill_f411ce
framework = arduino
upload_protocol = stlink
monitor_speed = 115200
monitor_port = COM3
lib_deps = 
    nrf24/RF24 @ ^1.6.0
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit Unified Sensor
debug_tool = stlink
build_flags = -I src/drivers